import React, { useState } from 'react';
import ExerciseEngine from '../components/exercises/ExerciseEngine';

const defaultJSON = `[
  {
    "id": "ex-tm-1",
    "type": "text-marking",
    "title": "Grammatik entdecken",
    "instruction": "Klicke auf die Konnektoren im Text, um sie zu markieren. Ordne sie dann im Tabelle ihrer Funktion zu.",
    "text": "Sie sind {c1:nicht nur} Nachbarn, {c1:sondern auch} beste Freunde. {c2:Einerseits} verbringen sie jede freie Minute zusammen, {c2:andererseits} respektieren sie auch die Freiräume des anderen.",
    "categories": [
      { "id": "c1", "label": "nicht nur ... sondern auch", "function": "Aufzählung (etwas Unerwartetes hinzufügen)" },
      { "id": "c2", "label": "Einerseits ... andererseits", "function": "Zwei Perspektiven gegenüberstellen" }
    ]
  },
  {
    "id": "ex1",
    "type": "fill-in-the-blanks",
    "title": "1. Lücken füllen",
    "instruction": "Ergänzen Sie die passenden Wörter.",
    "wordBank": ["Stieftochter", "leiblichen", "früheren Beziehungen", "Ehefrau", "ungewöhnlich"],
    "text": "Mein Name ist Carl. Wir leben in einer Familien-Konstellation, die heutzutage nicht {0} ist. Vor mir steht meine neue Partnerin und jetzige {1} Petra.",
    "answers": { "0": "ungewöhnlich", "1": "Ehefrau" }
  },
  {
    "id": "ex2",
    "type": "matching",
    "title": "2. Zwischenmenschliches",
    "instruction": "Was passt? Ordnen Sie zu.",
    "pairs": [
      { "id": "m1", "left": "eine Beziehung zu jemandem hat,", "right": "dann hat man eine positive Beziehung zu dieser Person." },
      { "id": "m2", "left": "Vertrauen zu jemandem hat,", "right": "dann kann man die Person verstehen." }
    ]
  },
  {
    "id": "ex3",
    "type": "multiple-choice",
    "title": "3. Nomen mit Präposition",
    "instruction": "Was ist richtig? Markieren Sie.",
    "questions": [
      {
        "id": "q1",
        "question": "Der Wunsch ___ einem eigenen Zimmer ist bei Kindern groß.",
        "options": ["nach", "von", "an"],
        "correctAnswer": "nach"
      }
    ]
  },
  {
    "id": "ex4",
    "type": "true-false",
    "title": "4. Richtig oder Falsch?",
    "instruction": "Lesen Sie den Text und markieren Sie.",
    "questions": [
      { "statement": "Die Schweiz hat vier offizielle Landessprachen.", "isTrue": true },
      { "statement": "In Genf spricht man vorwiegend Deutsch.", "isTrue": false }
    ]
  },
  {
    "id": "ex5",
    "type": "categorization",
    "title": "5. Artikel sortieren",
    "instruction": "Ordnen Sie die Nomen den passenden Artikeln zu.",
    "categories": ["der", "die", "das"],
    "items": [
      { "word": "Mädchen", "category": "das" },
      { "word": "Frau", "category": "die" },
      { "word": "Tisch", "category": "der" },
      { "word": "Buch", "category": "das" }
    ]
  },
  {
    "id": "ex6",
    "type": "ordering",
    "title": "6. Sätze ordnen",
    "instruction": "Bringen Sie die Sätze in die richtige Reihenfolge.",
    "items": [
      "Zuerst schalte ich den Computer ein.",
      "Dann öffne ich mein E-Mail-Programm.",
      "Danach lese ich die neuen Nachrichten.",
      "Zum Schluss antworte ich auf wichtige Mails."
    ]
  },
  {
    "id": "ex7",
    "type": "transformation",
    "title": "7. Sätze umformen (Passiv)",
    "instruction": "Formulieren Sie die Sätze ins Passiv um.",
    "items": [
      { "prompt": "Der Mechaniker repariert das Auto.", "modelAnswer": "Das Auto wird vom Mechaniker repariert." },
      { "prompt": "Man spricht hier Deutsch.", "modelAnswer": "Hier wird Deutsch gesprochen." }
    ]
  },
  {
    "id": "ex8",
    "type": "crossword",
    "title": "8. Kreuzworträtsel (Berufe)",
    "instruction": "Ergänzen Sie die Berufe.",
    "clues": [
      { "number": 1, "direction": "across", "clue": "Arbeitet im Krankenhaus", "answer": "ARZT", "row": 0, "col": 0 },
      { "number": 2, "direction": "down", "clue": "Bäckt Brot", "answer": "BAECKER", "row": 0, "col": 5 },
      { "number": 3, "direction": "across", "clue": "Fährt ein Taxi", "answer": "FAHRER", "row": 2, "col": 3 }
    ]
  }
]`;

const ExerciseTestPage = () => {
  const [jsonInput, setJsonInput] = useState(defaultJSON);
  const [parsedData, setParsedData] = useState(JSON.parse(defaultJSON));
  const [error, setError] = useState(null);

  const handleRender = () => {
    try {
      const data = JSON.parse(jsonInput);
      setParsedData(data);
      setError(null);
    } catch (e) {
      setError(e.message);
    }
  };

  return (
    <div
      className="bg-slate-50 px-4 sm:px-6 lg:px-8 flex flex-col flex-1 min-h-0"
      style={{ overflow: 'hidden' }}
    >
      {/* Header — fixed height */}
      <div className="max-w-7xl w-full mx-auto flex-shrink-0 mb-4">
        <h1 className="text-2xl font-bold text-slate-900 mb-1">Exercise Engine Test</h1>
        <p className="text-slate-600 text-sm">Paste JSON generated by Gemini/Claude here to see how it renders.</p>
      </div>

      {/* Two-pane area — takes all remaining height, never overflows page */}
      <div
        className="max-w-7xl w-full mx-auto flex-1 grid grid-cols-1 lg:grid-cols-2 gap-6 min-h-0 pb-6"
      >
        {/* ── Editor Side ─────────────────────────────────────────── */}
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 flex flex-col min-h-0 overflow-hidden">
          <div className="bg-slate-800 px-4 py-3 border-b border-slate-700 flex justify-between items-center flex-shrink-0">
            <span className="text-slate-200 font-mono text-sm">exercise_data.json</span>
            <button
              onClick={handleRender}
              className="bg-indigo-500 hover:bg-indigo-600 text-white px-4 py-1.5 rounded text-sm font-medium transition-colors"
            >
              Update Preview
            </button>
          </div>
          {error && (
            <div className="bg-red-50 text-red-600 p-3 text-sm border-b border-red-100 font-mono flex-shrink-0">
              Error: {error}
            </div>
          )}
          <textarea
            data-lenis-prevent="true"
            value={jsonInput}
            onChange={(e) => setJsonInput(e.target.value)}
            className="flex-1 min-h-0 w-full bg-slate-900 text-slate-100 font-mono p-4 resize-none focus:outline-none focus:ring-inset focus:ring-2 focus:ring-indigo-500 overflow-y-auto"
            spellCheck="false"
          />
        </div>

        {/* ── Preview Side ─────────────────────────────────────────── */}
        <div data-lenis-prevent="true" className="bg-slate-100 rounded-xl border-2 border-dashed border-slate-300 p-6 overflow-y-auto min-h-0">
          {parsedData && <ExerciseEngine exercises={parsedData} />}
        </div>
      </div>
    </div>
  );
};

export default ExerciseTestPage;
